Agriculture/urls.py
from django.contrib import admin
from django.urls import path,  include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("App_Shop.urls")),
    path("account/", include("App_Login.urls")),
    path('customer/', include("App_Customer.urls")),
    path("farmer/", include("App_Farmer.urls")),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Farmer/urls.py
from django.urls import path

from . import views
from .views import CreateProduct, CreateProfile

from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView
)

app_name = 'App_Farmer'

urlpatterns = [
    path('', views.main, name='farmer-home'),
    path('farmer/login/', views.farmer_login_user, name='farmer-login'),
    path('farmer/logout/', views.farmer_logout_user, name='farmer-logout'),
    path('farmer/signup/', views.farmer_sign_up, name='farmer-signup'),
    path('product/new/', CreateProduct.as_view(), name='Product-create'),
    path('article/', PostListView.as_view(), name='farmer-article'),
    path('view_profile/', views.view_profile, name='farmer-view-profile'),
    path('farmer/profile/', CreateProfile.as_view(), name='farmer-profile'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),

]

App_Shop/urls.py
from django.urls import path
from . import views

app_name = 'App_Shop'

urlpatterns = [

    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),

]

App_Farmer/models.py
from django.db import models

from django.utils import timezone
from django.conf import settings
from django.urls import reverse
from PIL import Image


class Profile(models.Model):
    username = models.CharField(max_length=264, blank=True)
    full_name = models.CharField(max_length=264, blank=True)
    profile_pic = models.ImageField(upload_to='farmer_profile_pics')
    address_1 = models.TextField(max_length=300, blank=True)
    city = models.CharField(max_length=40, blank=True)
    zipcode = models.CharField(max_length=10, blank=True)
    country = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=20, blank=True)


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='article_pics')

    def __str__(self):
        return f'{self.author} Post'

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

App_Login/models.py
from django.db import models

# To Create a Custom User Model and Admin Panel

from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.utils.translation import ugettext_lazy

# To automatically create one to one objects

from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


class MyUserManager(BaseUserManager):
    """ A custom Manager to deal with emails as unique identifer """
    def _create_user(self, email, password, **extra_fields):
        """ Creates and saves a user with a given email and password"""

        if not email:
            raise ValueError("The Email must be set!")

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True')
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, null=False)
    is_staff = models.BooleanField(
        ugettext_lazy('staff status'),
        default=False,
        help_text=ugettext_lazy('Designates whether the user can log in this site')
    )

    is_active = models.BooleanField(
        ugettext_lazy('active'),
        default=True,
        help_text=ugettext_lazy('Designates whether this user should be treated as active. Unselect this instead of deleting accounts')
    )

    USERNAME_FIELD = 'email'
    objects = MyUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    username = models.CharField(max_length=264, blank=True)
    full_name = models.CharField(max_length=264, blank=True)
    address_1 = models.TextField(max_length=300, blank=True)
    city = models.CharField(max_length=40, blank=True)
    zipcode = models.CharField(max_length=10, blank=True)
    country = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=20, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username + "'s Profile"

    def is_fully_filled(self):
        fields_names = [f.name for f in self._meta.get_fields()]

        for field_name in fields_names:
            value = getattr(self, field_name)
            if value is None or value == '':
                return False
        return True


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_profile(sender, instance, **kwargs):
    instance.profile.save()

App_Farmer/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings
from .models import Post  #Profile
from django.forms import forms

'''''
class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('profile_pic',)


class FarmerSignUpForm(UserCreationForm):
    class Meta:
        model = settings.AUTH_USER_MODEL
        fields = ('email', 'password1', 'password2',)

'''''


class PostForm(forms):
    class Meta:
        model = Post
        fields = ['title', 'content', 'author', 'image', ]
        

App_Farmer/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, reverse
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib import messages
#from .forms import FarmerSignUpForm #ProfileForm, PostForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from App_Shop.models import Product

from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from .models import Post, Profile


def main(request):
    return render(request, 'App_Farmer/home.html')


def farmer_login_user(request):
    return render(request, 'App_Farmer/farmer_login.html')


def farmer_logout_user(request):
    logout(request)
    messages.warning(request, "You are logged out!!")
    return HttpResponseRedirect(reverse('App_Farmer:farmer-home'))


def farmer_sign_up(request):
    return render(request, 'App_Farmer/farmer_sign_up.html')


class CreateProduct(CreateView):
    model = Product
    template_name = 'App_Shop/create_product.html'
    fields = ('mainimage', 'name', 'category', 'preview_text', 'detail_text', 'price', 'old_price',)

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


def article(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'App_Farmer/article.html', context)


class PostListView(ListView):
     model = Post
     template_name = 'App_Farmer/article.html'
     context_object_name = 'posts'
     ordering = ['-date_posted']
     paginate_by = 3


class UserPostListView(ListView):
    model = Post
    template_name = 'App_Farmer/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 3

    def get_queryset(self):
        user = get_object_or_404(settings.AUTH_USER_MODEL, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostDetailView(DetailView):
    model = Post


class PostCreateView(CreateView):
    model = Post
    fields = ['title', 'content']
    template_name = 'App_Farmer/create_post.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class CreateProfile(CreateView):
    model = Profile
    template_name = 'App_Farmer/create_profile.html'
    fields = ('username', 'full_name', 'profile_pic', 'address_1', 'city', 'zipcode', 'country', 'phone',)

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


def view_profile(request):
    context = {
        'profiles': Profile.objects.all()
    }
    return render(request, 'App_Farmer/profile.html', context)

templates/App_Farmer/create_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post</title>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">

  <link rel="stylesheet" type="text/css" href="/static/admin/css/nav_sidebar.css">
  <script src="/static/admin/js/nav_sidebar.js" defer></script>

<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">


<script src="/admin/jsi18n/"></script>
<script src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script src="/static/admin/js/calendar.js"></script>
<script src="/static/admin/js/jquery.init.js"></script>
<script src="/static/admin/js/admin/DateTimeShortcuts.js"></script>
<script src="/static/admin/js/core.js"></script>
<script src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script src="/static/admin/js/actions.js"></script>
<script src="/static/admin/js/urlify.js"></script>
<script src="/static/admin/js/prepopulate.js"></script>
<script src="/static/admin/js/vendor/xregexp/xregexp.js"></script>


    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">


<meta name="robots" content="NONE,NOARCHIVE">
</head>
<body>

  <fieldset class="module aligned ">



        <div class="form-row field-title">


                <div>


                        <label class="required" for="id_title">Title:</label>

                            <input type="text" name="title" class="vTextField" maxlength="200" required id="id_title">



                </div>

        </div>

        <div class="form-row field-content">


                <div>


                        <label class="required" for="id_content">Content:</label>

                            <textarea name="content" cols="40" rows="10" class="vLargeTextField" required id="id_content">
</textarea>



                </div>

        </div>

        <div class="form-row field-date_posted">


                <div>


                        <label class="required" for="id_date_posted_0">Date posted:</label>

                            <p class="datetime">
  Date: <input type="text" name="date_posted_0" value="2020-11-28" class="vDateField" size="10" required id="id_date_posted_0">

<br>
  Time: <input type="text" name="date_posted_1" value="17:11:45" class="vTimeField" size="8" required id="id_date_posted_1">


</p><input type="hidden" name="initial-date_posted_0" value="2020-11-28" id="initial-id_date_posted_0"><input type="hidden" name="initial-date_posted_1" value="17:11:45" id="initial-id_date_posted_1">



                </div>

        </div>

        <div class="form-row field-author">


                <div>


                        <label class="required" for="id_author">Author:</label>

                            <div class="related-widget-wrapper">
    <select name="author" required id="id_author">
  <option value="" selected>---------</option>

  <option value="1">admin@gmail.com</option>

</select>

        <a class="related-widget-wrapper-link change-related" id="change_id_author"
            data-href-template="/admin/App_Login/user/__fk__/change/?_to_field=id&amp;_popup=1"
            title="Change selected user"><img src="/static/admin/img/icon-changelink.svg" alt="Change"></a><a class="related-widget-wrapper-link add-related" id="add_id_author"
            href="/admin/App_Login/user/add/?_to_field=id&amp;_popup=1"
            title="Add another user"><img src="/static/admin/img/icon-addlink.svg" alt="Add"></a>

</div>



                </div>

        </div>

        <div class="form-row field-image">


                <div>


                        <label class="required" for="id_image">Image:</label>

                            <input type="file" name="image" accept="image/*" id="id_image">



                </div>

        </div>

</fieldset>

<div class="submit-row">

    <a href="{% url 'App_Farmer:farmer-home' %}">
        <input type="submit" value="Save" class="default" name="_save"></a>


</div>


    <script id="django-admin-form-add-constants"
            src="/static/admin/js/change_form.js"

                data-model-name="product"

            async>
    </script>




<script id="django-admin-prepopulated-fields-constants"
        src="/static/admin/js/prepopulate_init.js"
        data-prepopulated-fields="[]">
</script>





          <br class="clear">


        <div id="footer"></div>

</body>
</html>

templates/App_Farmer/create_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Profile</title>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">

  <link rel="stylesheet" type="text/css" href="/static/admin/css/nav_sidebar.css">
  <script src="/static/admin/js/nav_sidebar.js" defer></script>

<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">


<script src="/admin/jsi18n/"></script>
<script src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script src="/static/admin/js/jquery.init.js"></script>
<script src="/static/admin/js/core.js"></script>
<script src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script src="/static/admin/js/actions.js"></script>
<script src="/static/admin/js/urlify.js"></script>
<script src="/static/admin/js/prepopulate.js"></script>
<script src="/static/admin/js/vendor/xregexp/xregexp.js"></script>


    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">


<meta name="robots" content="NONE,NOARCHIVE">
</head>
<body>


  <fieldset class="module aligned ">



        <div class="form-row field-username">


                <div>


                        <label for="id_username">Username:</label>

                            <input type="text" name="username" class="vTextField" maxlength="264" id="id_username">



                </div>

        </div>

        <div class="form-row field-full_name">


                <div>


                        <label for="id_full_name">Full name:</label>

                            <input type="text" name="full_name" class="vTextField" maxlength="264" id="id_full_name">



                </div>

        </div>

        <div class="form-row field-profile_pic">


                <div>


                        <label class="required" for="id_profile_pic">Profile pic:</label>

                            <input type="file" name="profile_pic" accept="image/*" required id="id_profile_pic">



                </div>

        </div>

        <div class="form-row field-address_1">


                <div>


                        <label for="id_address_1">Address 1:</label>

                            <textarea name="address_1" cols="40" rows="10" class="vLargeTextField" maxlength="300" id="id_address_1">
</textarea>



                </div>

        </div>

        <div class="form-row field-city">


                <div>


                        <label for="id_city">City:</label>

                            <input type="text" name="city" class="vTextField" maxlength="40" id="id_city">



                </div>

        </div>

        <div class="form-row field-zipcode">


                <div>


                        <label for="id_zipcode">Zipcode:</label>

                            <input type="text" name="zipcode" class="vTextField" maxlength="10" id="id_zipcode">



                </div>

        </div>

        <div class="form-row field-country">


                <div>


                        <label for="id_country">Country:</label>

                            <input type="text" name="country" class="vTextField" maxlength="50" id="id_country">



                </div>

        </div>

        <div class="form-row field-phone">


                <div>


                        <label for="id_phone">Phone:</label>

                            <input type="text" name="phone" class="vTextField" maxlength="20" id="id_phone">



                </div>

        </div>

</fieldset>





<div class="submit-row">

    <a href="{% url 'App_Farmer:farmer-home' %}">
        <input type="submit" value="Save" class="default" name="_save"></a>


</div>


    <script id="django-admin-form-add-constants"
            src="/static/admin/js/change_form.js"

                data-model-name="product"

            async>
    </script>




<script id="django-admin-prepopulated-fields-constants"
        src="/static/admin/js/prepopulate_init.js"
        data-prepopulated-fields="[]">
</script>





          <br class="clear">


        <div id="footer"></div>

</body>
</html>

templates/App_Farmer/farmer_login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Farmer Login</title>
</head>
<body>

<center>
<br>
<h2 style="color:#FF4C33">Digital Agriculture Management System</h2>
<img src="/media/images.jpeg"  width="300" height="300">
<img src="/media/image1.jpeg"  width="300" height="300">
    <p style="color:#0B0302">You have come to the right place to sell your product</p>
    <p style="color:#0B0302">click Login Button and Continue</p>
<h2>Login:</h2>
<table class="table">
    <tr>
        <td><label for="id_username">Username</label></td>
        <td><input id="id_username" name="username"
                   type="text" class="form-control"></td>
    </tr>
    <tr>
        <td><label for="id_password">Password</label></td>
        <td><input id="id_password" name="password"
                   type="password" class="form-control"></td>
    </tr>
</table>

    <a href="{% url 'App_Farmer:farmer-home' %}"><button type="submit" class="btn btn-success btn-sm">  LOG IN </button></a>


<br>
<p>Doesn't have an account? <a href="{% url 'App_Farmer:farmer-signup' %}">Sing Up Here</a></p>
</center>
</body>
</html>

templates/App_Farmer/farmer_sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Farmer SignUp</title>
</head>
<body>

<center>
<div class='container'>
	<div class ='messages container mt-2'>

	</div>
</div>

</div>
	<h2>Create New Account:</h2>



<div id="div_id_email" class="form-group">
	<label for="id_email" class=" requiredField">
                Email<span class="asteriskField">*</span>
	</label>

	<div class="">
	  <input type="email" name="email" maxlength="254" autofocus class="emailinput form-control" required id="id_email">
	</div>
</div>
	<div id="div_id_password1" class="form-group">
		<label for="id_password1" class=" requiredField">
                Password<span class="asteriskField">*</span>
		</label>

		<div class="">
			 <input type="password" name="password1" autocomplete="new-password" class="textinput textInput form-control" required id="id_password1">
		     <small id="hint_id_password1" class="form-text text-muted">
				 <ul>
			         <li>Your password can’t be too similar to your other personal information.</li>
			          <li>Your password must contain at least 8 characters.</li>
			          <li>Your password can’t be a commonly used password.</li>
				      <li>Your password can’t be entirely numeric.</li>
			     </ul>
			 </small>
		</div>
	</div>
	<div id="div_id_password2" class="form-group">
		<label for="id_password2" class=" requiredField">
                Password confirmation<span class="asteriskField">*</span>
		</label>
		<div class="">
			<input type="password" name="password2" autocomplete="new-password" class="textinput textInput form-control" required id="id_password2">
			<small id="hint_id_password2" class="form-text text-muted">Enter the same password as before, for verification.</small>
		</div>
	</div>
	<br>
	<input type="hidden" name="csrfmiddlewaretoken" value="f43sYWzGfPygeRaYNBmoMD74KdXD0ML5vyVU8FKxxebhTSW3uXftCHGdO7UbL2f6">
	<a href="{% url 'App_Farmer:farmer-login' %}">
		<button type="submit" class="btn btn-success btn-sm" >
			Create Account
		</button></a>

	<br>
	<p>Already have an account? <a href="{% url 'App_Farmer:farmer-login' %}">Login Here</a></p>


 </div>

</center>

</body>
</html>

templates/App_Farmer/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Digital Agriculture Management System</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-123322969-2"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-123322969-2');
	</script>

	<style>

		#logo{
		}

		body{
			background-color: #ebeff5;
		}


		#total-orders{
			background-color: #4cb4c7;
		}


		#orders-delivered{
			background-color: #7abecc;
		}

		#orders-pending{
			background-color: #7CD1C0;
		}




	</style>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
 <div class="container">
	  <a href="{% url 'App_Farmer:farmer-home' %}"><button type="submit" class="btn btn-success btn-sm">Dashboard</button></a>
      <a href="{% url 'App_Farmer:Product-create' %}"><button type="submit" class="btn btn-success btn-sm">  Product </button></a>
      <a href="{% url 'App_Farmer:farmer-article' %}" ><button type="submit" class="btn btn-success btn-sm"> Article </button></a>
      <a href="{% url 'App_Farmer:post-create' %}" ><button type="submit" class="btn btn-success btn-sm"> Post </button></a>
      <a href="{% url 'App_Farmer:farmer-profile' %}" ><button type="submit" class="btn btn-success btn-sm"> Create Profile </button></a>
      <a href="{% url 'App_Farmer:farmer-view-profile' %}" ><button type="submit" class="btn btn-success btn-sm">  View Profile </button></a>
     <a href="{% url 'App_Shop:home' %}" ><button type="submit" class="btn btn-success btn-sm">Log out</button></a>
 	 <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
 	 aria-expanded="false" aria-label="Toggle navigation">
 	 	<span class="navbar-toggler-icon"></span>
    </button>
 </div>
</nav>
<br>

<br>

<div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="total-orders">
			  	<div class="card-header">
			  		<h5 class="card-title" style="color:#E81919">Total Orders</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title" style="color:#E89A19">0</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-delivered">
			  	<div class="card-header">
			  		<h5 class="card-title" style="color:#E81919">Orders Delivered</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title" style="color:#E89A19">0</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-pending">
			  	<div class="card-header">
			  		<h5 class="card-title" style="color:#E81919">Orders Pending</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title" style="color:#E89A19">0</h3>
			  	</div>
			</div>
		</div>
	</div>
</div>

<br>
<br>

<div class="row">
	<div class="col-md-5">
		<h5>CUSTOMERS:</h5>
		<hr>
		<div class="card card-body">
			<a class="prevent-submit btn btn-primary  btn-sm btn-block" href="">Create Customer</a>
			<table class="table table-sm">
				<tr>
					<th></th>
					<th>Customer</th>
					<th>Phone</th>
				</tr>

					<tr>
						<td><a class="btn btn-sm btn-info" href="/customer/2/">View</a></td>
						<td></td>
						<td></td>
					</tr>

					<tr>
						<td><a class="btn btn-sm btn-info" href="/customer/4/">View</a></td>
						<td></td>
						<td></td>
					</tr>


			</table>
		</div>
	</div>

	<div class="col-md-7">
		<h5>LAST 5 ORDERS</h5>
		<hr>
		<div class="card card-body">

			<table class="table table-sm">
				<tr>
					<th>Product</th>
					<th>Date Orderd</th>
					<th>Status</th>
					<th>Update</th>
					<th>Remove</th>
				</tr>


					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td><a class="btn btn-sm btn-info" href="/update_order/3/">Update</a></td>

						<td><a class="btn btn-sm btn-danger" href="/delete_order/3/">Delete</a></td>

					</tr>

					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td><a class="btn btn-sm btn-info" href="/update_order/11/">Update</a></td>

						<td><a class="btn btn-sm btn-danger" href="/delete_order/11/">Delete</a></td>

					</tr>

					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td><a class="btn btn-sm btn-info" href="/update_order/14/">Update</a></td>

						<td><a class="btn btn-sm btn-danger" href="/delete_order/14/">Delete</a></td>

					</tr>

					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td><a class="btn btn-sm btn-info" href="/update_order/15/">Update</a></td>

						<td><a class="btn btn-sm btn-danger" href="/delete_order/15/">Delete</a></td>

					</tr>

					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td><a class="btn btn-sm btn-info" href="/update_order/16/">Update</a></td>

						<td><a class="btn btn-sm btn-danger" href="/delete_order/16/">Delete</a></td>

					</tr>

			</table>
		</div>
	</div>

</div>
<hr>


</body>
</html>

templates/App_Farmer/logout.html
{% extends 'base.html' %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
           <a href="{% url 'App_Farmer:farmer-login' %}" class="btn btn-primary">Farmer</a>
        </small>
    </div>
{% endblock content %}