Agriculture/urls.py
from django.contrib import admin
from django.urls import path,  include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("App_Shop.urls")),
    path("account/", include("App_Login.urls")),
    path('customer/', include("App_Customer.urls")),
    path("farmer/", include("App_Farmer.urls")),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Farmer/urls.py
from django.urls import path

from . import views
from .views import CreateProduct, CreateProfile

from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView
)

app_name = 'App_Farmer'

urlpatterns = [
    path('', views.main, name='farmer-home'),
    path('farmer/login/', views.farmer_login_user, name='farmer-login'),
    path('farmer/logout/', views.farmer_logout_user, name='farmer-logout'),
    path('farmer/signup/', views.farmer_sign_up, name='farmer-signup'),
    path('product/new/', CreateProduct.as_view(), name='Product-create'),
    path('article/', PostListView.as_view(), name='farmer-article'),
    path('view_profile/', views.view_profile, name='farmer-view-profile'),
    path('farmer/profile/', CreateProfile.as_view(), name='farmer-profile'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),

]

App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name='add'),
    path('cart', views.cart_view, name='cart'),
    path('remove/<pk>/', views.remove_from_cart, name='remove'),
    path('increase/<pk>/', views.increase_cart, name='increase'),
    path('decrease/<pk>/', views.decrease_cart, name='decrease'),

]

App_Shop/urls.py
from django.urls import path
from . import views

app_name = 'App_Shop'

urlpatterns = [

    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),

]

App_Shop/models.py
from django.db import models


# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Categories"


class Product(models.Model):
    mainimage = models.ImageField(upload_to="Products")
    name = models.CharField(max_length=264)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    preview_text = models.TextField(max_length=200, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=1000, verbose_name='Description')
    price = models.FloatField()
    old_price = models.FloatField(default=0.00)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created', ]

App_Shop/views.py
from django.shortcuts import render
from .models import Product

# import views
from django.views.generic import ListView, DetailView

# Mixin
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

class Home(ListView):
    model = Product
    template_name = 'App_Shop/home.html'


class ProductDetail(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'App_Shop/product_detail.html'

templates/App_Shop/create_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Product</title>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">

  <link rel="stylesheet" type="text/css" href="/static/admin/css/nav_sidebar.css">
  <script src="/static/admin/js/nav_sidebar.js" defer></script>

<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">


<script src="/admin/jsi18n/"></script>
<script src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script src="/static/admin/js/jquery.init.js"></script>
<script src="/static/admin/js/core.js"></script>
<script src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script src="/static/admin/js/actions.js"></script>
<script src="/static/admin/js/urlify.js"></script>
<script src="/static/admin/js/prepopulate.js"></script>
<script src="/static/admin/js/vendor/xregexp/xregexp.js"></script>


    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">


<meta name="robots" content="NONE,NOARCHIVE">
</head>
<body>

  <fieldset class="module aligned ">



        <div class="form-row field-mainimage">


                <div>


                        <label class="required" for="id_mainimage">Mainimage:</label>

                            <input type="file" name="mainimage" accept="image/*" required id="id_mainimage">



                </div>

        </div>

        <div class="form-row field-name">


                <div>


                        <label class="required" for="id_name">Name:</label>

                            <input type="text" name="name" class="vTextField" maxlength="264" required id="id_name">



                </div>

        </div>

        <div class="form-row field-category">


                <div>


                        <label class="required" for="id_category">Category:</label>

                            <div class="related-widget-wrapper">
    <select name="category" required id="id_category">
  <option value="" selected>---------</option>

</select>

        <a class="related-widget-wrapper-link change-related" id="change_id_category"
            data-href-template="/admin/App_Shop/category/__fk__/change/?_to_field=id&amp;_popup=1"
            title="Change selected category"><img src="/static/admin/img/icon-changelink.svg" alt="Change"></a><a class="related-widget-wrapper-link add-related" id="add_id_category"
            href="/admin/App_Shop/category/add/?_to_field=id&amp;_popup=1"
            title="Add another category"><img src="/static/admin/img/icon-addlink.svg" alt="Add"></a>

</div>



                </div>

        </div>

        <div class="form-row field-preview_text">


                <div>


                        <label class="required" for="id_preview_text">Preview Text:</label>

                            <textarea name="preview_text" cols="40" rows="10" class="vLargeTextField" maxlength="200" required id="id_preview_text">
</textarea>



                </div>

        </div>

        <div class="form-row field-detail_text">


                <div>


                        <label class="required" for="id_detail_text">Description:</label>

                            <textarea name="detail_text" cols="40" rows="10" class="vLargeTextField" maxlength="1000" required id="id_detail_text">
</textarea>



                </div>

        </div>

        <div class="form-row field-price">


                <div>


                        <label class="required" for="id_price">Price:</label>

                            <input type="number" name="price" step="any" required id="id_price">



                </div>

        </div>

        <div class="form-row field-old_price">


                <div>


                        <label class="required" for="id_old_price">Old price:</label>

                            <input type="number" name="old_price" value="0.0" step="any" required id="id_old_price">



                </div>

        </div>

</fieldset>

<div class="submit-row">

    <a href="{% url 'App_Farmer:farmer-home' %}">
        <input type="submit" value="Save" class="default" name="_save"></a>


</div>


    <script id="django-admin-form-add-constants"
            src="/static/admin/js/change_form.js"

                data-model-name="product"

            async>
    </script>




<script id="django-admin-prepopulated-fields-constants"
        src="/static/admin/js/prepopulate_init.js"
        data-prepopulated-fields="[]">
</script>


</div>
</div>


          <br class="clear">
        </div>

        <div id="footer"></div>
      </div>
    </div>
</div>
</body>
</html>

templates/App_Shop/home.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container my-5">
	<h2 class='my-5'>Featured Products</h2>
	<div class="row">
	{% for product in object_list %}
	  <div class="col-md-6 col-sm-12 col-lg-3">
	  	<figure class="card card-product">
	  		<div class="img-wrap">
	  			<img src='/media/{{ product.mainimage }}' style="width: 100%; height: 300px;">
	  		</div>
	  		<figurecaption class='info-wrap'>
	  			<h6 class="title"><a href="{% url 'App_Shop:product_detail' pk=product.pk %}">{{ product.name }}</a></h6>
	  			<div class="action-wrap">
	  				<div class="price-wrap h5">
	  					<span class="price-new"> &#2547;{{ product.price|floatformat:2 }}</span>
	  					<span class="price-old"><strike> &#2547;{{ product.old_price|floatformat:2 }}</strike></span>
	  				</div>
	  			</div>
	  		</figurecaption>BANK
	  	</figure>
	  </div>
	{% endfor %}
</div>
</div>
{% endblock %}

templates/App_Shop/product_detail.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container my-5">
  <div class="card">
    <div class="row">
      <aside class="col-sm-5 border-right">
        <article class="gallery-wrap">
          <div class="img-big-wrap">
            <div>
              <a href="#"><img src="/media/{{ object.mainimage }}" style="width:450px"></a>
            </div>
          </div>
        </article>
      </aside>
      <aside class="col-sm-7">
        <article class="card-body p-5">
          <h3 class="title mp-3">{{ object.name }}</h3>
          <p class="price-detail-wrap">
            <span class="price h3 text-warning">
              <span class="currency">BDT &#2547;</span><span class="num">{{ object.price }}</span>
            </span>
          </p>
          <dl class="item-property">
            <dt>Description</dt>
            <dd>
              <p>{{ object.detail_text | linebreaks }}</p>
            </dd>
          </dl>
          <br>
          <a href="{% url 'App_Order:add' pk=object.pk %}" class="btn btn-lg btn-outline-primary text-uppercase"> <i class="fas fa-shopping-cart"></i> Add to Cart</a>
        </article>
      </aside>
    </div>
  </div>
</div>
{% endblock %}