Agriculture/urls.py
from django.contrib import admin
from django.urls import path,  include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("App_Shop.urls")),
    path("account/", include("App_Login.urls")),
    path('customer/', include("App_Customer.urls")),
    path("farmer/", include("App_Farmer.urls")),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Customer/urls.py
from django.urls import path
from . import views
app_name = 'App_Customer'

urlpatterns = [
    path('', views.main, name='customer-login'),
]

App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
]

App_Shop/urls.py
from django.urls import path
from . import views

app_name = 'App_Shop'

urlpatterns = [

    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),

]

App_Customer/models.py
from django.db import models

# Create your models here.

App_Customer/views.py
from django.shortcuts import render


def main(request):
    return render(request, 'App_Customer/customer_login.html')

templates/App_Customer/customer_login.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Customer Login </title>
</head>
<body>
{% block body_block %}
<br>
<center>
<h2 style="color:#FF4C33">Digital Agriculture Management System</h2>
<img src="/media/CustomerCare_Header-2.png"  width="300" height="300">
    <p style="color:#0B0302">You can purchase the best and most nutritious products from this website</p>
    <p style="color:#0B0302">click Login Button and Purchase Product</p>
 <a href="{% url 'App_Login:login' %}" class="btn btn-primary">Login</a>
</center>
{% endblock %}
</body>
</html>